### PR TITLE
Make Registrar exchange, admin, oracle upgradable

### PR DESCRIPTION
**Pull request by cloudhead**
The Registrar contract itself won't be upgradable, but its parts will be!

### CODE REVIEW

**Review by CodeSandwich — COMMENTED** [review]
Looks good, but should the registrar be non-upgradable? If so, shouldn't it get at least discardable and allow changing the owner of the ENS subdomain?

**Comment by cloudhead** [comment]
Hmm, I wonder how that would work?

**Comment by CodeSandwich** [comment]
Something as simple as this would allow us to create a new version of the registrar and make the ENS acknowledge it:
```
function setDomainOwner(address newOwner) public adminOnly {
    ens.setSubnodeOwner(keccak256("eth"), keccak256("radicle"), newOwner);
}
```

**Comment by cloudhead** [comment]
Done!

**Review by CodeSandwich — APPROVED** [review]
Nice!

**Pull request merged**
