### PR TITLE
Add events to org contract

### PR DESCRIPTION
**Pull request by cloudhead**

### CODE REVIEW

**Review by xla — APPROVED** [review]
🕍 ✒️ 👀 🔹

**Review by NunoAlexandre — APPROVED** [review]
Wanna add some tests?

**Comment by cloudhead** [comment]
Don't think there's anything to test here..

**Comment by NunoAlexandre** [comment]
> Don't think there's anything to test here..

Testing that the events are created appropriately, but I'm good like this.

**Pull request merged**
